name: laccuracy
version: '1.1.1'
main: com.grablins.laccuracy.Laccuracy
api-version: '1.21'
commands:
  setaccuracy:
    description: Sets the accuracy of a mob.
    usage: /setaccuracy <mob> <value>
  getaccuracy:
    description: Gets the current set accuracy of a mob.
    usage: /getaccuracy <mob>